[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain/" }
ports = { path = "../ports/" }
uuid = { workspace = true }
trait-variant = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
