[package]
name = "ports"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
domain = { path = "../domain/" }
trait-variant = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
