[package]
name = "out_postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { workspace = true }
diesel_migrations = { workspace = true }
domain = { path = "../../../core/domain" }
uuid = { workspace = true }
ports = { path = "../../../core/ports/" }
r2d2 = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
tokio = { workspace = true }
diesel = { workspace = true }
uuid = { workspace = true }

[profile.dev]
incremental = false
codegen-units = 1
