# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
with_docs = true

[print_schema.courier]
file = "src/courier/courier_schema.rs"
with_docs = true

[print_schema.order]
file = "src/order/order_schema.rs"
with_docs = true

[print_schema.storage_place]
file = "src/storage_place/storage_place_schema.rs"
with_docs = true

[print_schema.outbox]
file = "src/outbox/outbox_schema.rs"
with_docs = true

[migrations_directory]
dir = "migrations"
